### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.io.gfile' has no attribute 'get_filesystem'

### ISSUE THREAD

**Issue by nikpap123** [mikeizbicki/cmc-csci181#56]
I am using the code provided in the lecture video but I am getting the following error: 
AttributeError: module 'tensorflow._api.v1.io.gfile' has no attribute 'get_filesystem'

Has anyone encountered a similar problem?

**Comment by mikeizbicki** [comment]
You need to fix ensure that your versions of pytorch and tensorboard are compatible.  See #40 for the versions I used.

**Comment by nikpap123** [comment]
Fixed the versions but I am continuing to get that error. Are there any other version upgrades required?

**Comment by mikeizbicki** [comment]
@nikpap123 My guess is that you didn't actually fix the versions, and have some old versions still around.  Lot's of people have run into this issue on the assignment, and that's been the case for everyone so far.  Python is notoriously difficult to get package versions correct in, and package managers like anaconda make this problem more difficult (IMNSHO).  For example, uninstalling through pip/anaconda/etc doesn't actually remove packages for lots of complex reasons, and keeps lots of metadata around about your installations.

My recommendation is to delete your python install and reinstalling the packages from scratch.

**Comment by benfig1127** [comment]
@nikpap123 hey nick, I was in office hours today and Mike walked me through a full example of how to fix this issue so if you are still having trouble, feel free to add me on Facebook and I can help you with it.
